### ISSUE TITLE
feat: Add a CLI flag to save config changes to any specified .yaml file

### ISSUE THREAD

**Issue by Prana-vvb** [acmpesuecc/bal.rs#2]
Add a new CLI flag, for example, `--save-config [file.yaml]`, that users can pass when executing configuration commands.

- The flag should allow users to specify the path to the .yaml file where the configuration changes should be written.
- If the specified .yaml file already exists, the changes will be merged with existing configurations. If not, a new .yaml file should be created. If no path is specified, merge with the default `config.yaml` file

**Comment by pushkar-gr** [comment]
Kodo Baversy

**Comment by Prana-vvb** [comment]
!assign @pushkar-gr

**Comment by Prana-vvb** [comment]
!bounty 205

**Comment by bwaklog** [comment]
!deassign

**Comment by bwaklog** [comment]
@pushkar-gr you are free to work on other issues
