### ISSUE TITLE
improvement: Complete packet inspection for incoming requests

### ISSUE THREAD

**Issue by Prana-vvb** [acmpesuecc/bal.rs#3]
The current implementation in `lb.rs` at line 306 reads incoming request details and prints them out.  Finish the functionality that processes and inspects incoming packets. 

It should be able to:
- Inspect incoming requests to find anomalies (For testing, make it detect if a specified word or set of words are present. The set should be able to be configured in the yaml file)
- Optionally be able to log details about the request

**Comment by pushkar-gr** [comment]
Me!!!

**Comment by Prana-vvb** [comment]
!assign @pushkar-gr

**Comment by Prana-vvb** [comment]
!deassign @pushkar-gr

**Comment by Prana-vvb** [comment]
!assign @pushkar-gr

**Comment by pushkar-gr** [comment]
@Prana-vvb

**Comment by Prana-vvb** [comment]
!deassign @pushkar-gr

**Comment by Prana-vvb** [comment]
!assign @pushkar-gr  60

**Comment by Prana-vvb** [comment]
!assign @pushkar-gr

**Comment by Prana-vvb** [comment]
!deassign @pushkar-gr

**Comment by Prana-vvb** [comment]
!assign @pushkar-gr 60

**Comment by Prana-vvb** [comment]
!deassign @pushkar-gr

**Comment by Prana-vvb** [comment]
!deassign @pushkar-gr

**Comment by Prana-vvb** [comment]
!assign @pushkar-gr

**Comment by Prana-vvb** [comment]
!deassign
