### ISSUE TITLE
build: Add a bash script to install prerequisites(Rust) and build the project using cargo build

### ISSUE THREAD

**Issue by Prana-vvb** [acmpesuecc/bal.rs#6]
Check if Rust is installed first!!!

**Comment by pratham-exe** [comment]
Can i be assigned to this issue.

**Comment by Prana-vvb** [comment]
!assign @pratham-exe

**Comment by Prana-vvb** [comment]
@pratham-exe it's not complete. Continue working on it

**Comment by Prana-vvb** [comment]
@pratham-exe do you want an extension?

**Comment by pratham-exe** [comment]
Can I know what should be added ?

**Comment by Prana-vvb** [comment]
@pratham-exe it does not work completely. Do you want to work on it more?

**Comment by Prana-vvb** [comment]
!deassign @pratham-exe

**Comment by Prana-vvb** [comment]
!assign @pratham-exe

**Comment by Prana-vvb** [comment]
!deassign @pratham-exe
