### ISSUE TITLE
test: Add a bash script to test the load balancer using Vegeta

### ISSUE THREAD

**Issue by Prana-vvb** [acmpesuecc/bal.rs#8]
Install Vegeta from [here](https://github.com/tsenart/vegeta/releases), start the Load Balancer and try out
```
echo "GET http://127.0.0.1:8000" | ./vegeta.exe attack -rate="1000/s" -duration=1s | ./vegeta.exe report
```
to see if Vegeta works.

- The script should accept user input for rate
- Ensure that the input is a natural number

This command should set the rate as 100 and run Vegeta
```
$ ./test.sh 100
```

**Comment by Ishanvee** [comment]
Can i be assigned?

**Comment by Prana-vvb** [comment]
!assign @Ishanvee 45

**Comment by Prana-vvb** [comment]
@Ishanvee looks like you're assigned to another issue. Please check it out

**Comment by QWERTY-Ak** [comment]
can i be assigned this

**Comment by Prana-vvb** [comment]
!assign @QWERTY-Ak

**Comment by QWERTY-Ak** [comment]
unassign me

**Comment by Prana-vvb** [comment]
You can use ! withdraw to unassign yourself

**Comment by Prana-vvb** [comment]
!unassign @QWERTY-Ak

**Comment by VulcanRaven737** [comment]
Hey can I get assigned to this!

**Comment by Prana-vvb** [comment]
!assign @VulcanRaven737

**Comment by Prana-vvb** [comment]
!deassign @QWERTY-Ak

**Comment by Prana-vvb** [comment]
!assign @VulcanRaven737

**Comment by Prana-vvb** [comment]
@VulcanRaven737 it seems you are already assigned to another issue

**Comment by VulcanRaven737** [comment]
Hey, can you please try now? I got deassigned from the other issue

**Comment by Prana-vvb** [comment]
!assign @VulcanRaven737

**Comment by mebinthattil** [comment]
Can I be assigned this issue please

**Comment by Prana-vvb** [comment]
!assign @mebinthattil

**Comment by Prana-vvb** [comment]
Have you been assigned to another issue @mebinthattil ?

**Comment by Prana-vvb** [comment]
You can start working on it @mebinthattil

**Comment by mebinthattil** [comment]
> Have you been assigned to another issue @mebinthattil ?

No, I don’t think so

**Comment by mebinthattil** [comment]
I have a doubt, after implementing it, should I modify the readme file so that is mentions to change modification permission to executable in order to run the bash script?

**Comment by Prana-vvb** [comment]
Do not modify the readme. Just implement the script

**Comment by Prana-vvb** [comment]
!deassign @mebinthattil
